#!/usr/bin/env python3
"""merge_modules.py — concatenate the modules a manifest lists, and keep a map
back to where every merged line came from.

Author: Manish Jagdish Thatte
© Manish Jagdish Thatte

ManiT has no cross-file bodies (see src/kernel.manifest for the measurement),
so a multi-module program is a concatenated one. `cat a.mt b.mt > merged.mt`
does that in one line and throws away the only thing that made the modules
worth having separately: every diagnostic then names a line in a file nobody
wrote, and the reader has to count.

So this writes a SIDECAR MAP beside the merged source and can translate for
you:

    python3 tools/merge_modules.py src/kernel.manifest -o build/kernel.mt
    python3 tools/merge_modules.py --locate 1847 build/kernel.mt
        build/kernel.mt:1847  ->  src/kernel/scheduler.mt:132

The merged file is written under build/ rather than /tmp on purpose: it is the
translation unit every diagnostic will name, and a line number is worthless if
the file it points into has been overwritten by the next build.
"""

import argparse
import os
import sys

BANNER = "// " + "=" * 74


def read_manifest(path):
    """Return the module paths a manifest lists, in order.

    Blank lines and `#` comments are ignored. A path is resolved relative to
    the REPOSITORY ROOT (the manifest's own directory's parent), not to the
    caller's cwd, so the manifest reads the same from anywhere.
    """
    root = os.path.dirname(os.path.dirname(os.path.abspath(path)))
    mods = []
    with open(path) as f:
        for lineno, raw in enumerate(f, 1):
            line = raw.split("#", 1)[0].strip()
            if not line:
                continue
            full = os.path.join(root, line)
            if not os.path.isfile(full):
                sys.exit(
                    "error: %s:%d names a module that does not exist: %s"
                    % (path, lineno, line)
                )
            mods.append((line, full))
    if not mods:
        sys.exit("error: %s lists no modules" % path)
    return mods


def merge(manifest, out_path):
    mods = read_manifest(manifest)
    out_lines = []
    index = []   # (first merged line of this module, module path, module line count)

    header = [
        BANNER,
        "// GENERATED by tools/merge_modules.py from %s — DO NOT EDIT."
        % os.path.basename(manifest),
        "//",
        "// Edit the modules this was built from. The map beside this file",
        "// (%s.map) says which line came from where, and" % os.path.basename(out_path),
        "//     python3 tools/merge_modules.py --locate <N> %s" % out_path,
        "// will tell you directly.",
        "//",
        "// © Manish Jagdish Thatte",
        BANNER,
        "",
    ]
    out_lines.extend(header)

    for rel, full in mods:
        with open(full) as f:
            body = f.read().split("\n")
        # A trailing newline in the file gives a final empty element; drop it
        # so the module's line count is what an editor would report.
        if body and body[-1] == "":
            body.pop()
        start = len(out_lines) + 4   # after this module's 3 banner lines + blank
        out_lines.append(BANNER)
        out_lines.append("// %s  (%d lines)" % (rel, len(body)))
        out_lines.append(BANNER)
        out_lines.append("")
        index.append((start, rel, len(body)))
        out_lines.extend(body)
        out_lines.append("")

    os.makedirs(os.path.dirname(os.path.abspath(out_path)) or ".", exist_ok=True)
    with open(out_path, "w") as f:
        f.write("\n".join(out_lines) + "\n")

    with open(out_path + ".map", "w") as f:
        f.write("# merged_first_line\tmodule\tmodule_lines\n")
        f.write("# generated by tools/merge_modules.py — see --locate\n")
        for start, rel, n in index:
            f.write("%d\t%s\t%d\n" % (start, rel, n))

    return mods, index, len(out_lines)


def locate(merged_path, n):
    """Translate a line number in the merged file back to module:line."""
    map_path = merged_path + ".map"
    if not os.path.isfile(map_path):
        sys.exit("error: no map beside %s — was it produced by this tool?" % merged_path)
    entries = []
    with open(map_path) as f:
        for line in f:
            if line.startswith("#"):
                continue
            start, rel, count = line.rstrip("\n").split("\t")
            entries.append((int(start), rel, int(count)))
    for start, rel, count in entries:
        if start <= n < start + count:
            return "%s:%d  ->  %s:%d" % (merged_path, n, rel, n - start + 1)
    # Not inside a module body: it is one of the generated banners.
    return (
        "%s:%d  ->  (a banner line generated by merge_modules.py, "
        "not from any module)" % (merged_path, n)
    )


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("manifest", help="the manifest to merge, or (with --locate) "
                                     "the merged file to look a line up in")
    ap.add_argument("-o", "--output", help="path to write the merged source to")
    ap.add_argument("--locate", type=int, metavar="N",
                    help="translate line N of the merged file back to module:line")
    ap.add_argument("--quiet", action="store_true")
    args = ap.parse_args()

    if args.locate is not None:
        print(locate(args.manifest, args.locate))
        return

    if not args.output:
        ap.error("-o/--output is required when merging")

    mods, index, total = merge(args.manifest, args.output)
    if not args.quiet:
        print("merged %d modules -> %s (%d lines)" % (len(mods), args.output, total))
        print("  map: %s.map" % args.output)


if __name__ == "__main__":
    main()
